### ISSUE TITLE
issue with withdrawal address

### ISSUE THREAD

**Issue by adrienlacombe** [kilnfi/app-plugin-kiln#3]
Why so many 0 here https://github.com/skillz-blockchain/app-plugin-kiln/blob/main/tests/snapshots/nanos_deposit/00003.png ? I don't think we need those.

**Comment by aimxhaisse** [comment]
Yup we change shrink it considering we only handle eth 1 addresses in the end (format of withdrawal addresses for deposits can be longer as it also handles BLS addresses from eth2).

**Comment by aimxhaisse** [comment]
It was actually a bug, fixed in a603b7cab536f1c2d04f9b994d82f60b3280a0ad
